version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - cluster.name=elasticsearch_shuai
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - transport.host= 0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
  ms:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: registry.gitlab.com/szheng3/java-es
    volumes:
      # Cache maven dependencies
      - $HOME/.m2:/root/.m2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - elasticsearch
    networks:
      - backend
      - ext
    depends_on:
      - elasticsearch




volumes:
  esdata1:
    driver: local
networks:
  backend:
    internal: true
  ext:
    driver: bridge
